version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  push:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
    # TODO: use redocly/cli image
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Push"
          environment: 
            VCS: << pipeline.project.type >>
            PROVIDER: << pipeline.trigger_parameters.circleci.trigger_type >>
            CURRENT_BRANCH: << pipeline.git.branch >>
            COMMIT_SHA: << pipeline.git.revision >>
          command: |-
          
            if [[ $PROVIDER == 'github_app' ]]; then
              DEFAULT_BRANCH="<< trigger_parameters.github_app.default_branch >>"; 
              AUTHOR="<< trigger_parameters.github_app.commit_author_name >> <<< trigger_parameters.github_app.commit_author_email >>>"
              COMMIT_TIMESTAMP="<< trigger_parameters.github_app.commit_timestamp >>";
              REPOSITORY="<< trigger_parameters.github_app.project_id >>"
              NAMESPACE="<< trigger_parameters.github_app.repo_name >>";
              COMMIT_URL="<< trigger_parameters.github_app.web_url >>/commit/$COMMIT_SHA";
            elif [[ $PROVIDER == 'gitlab' ]]; then
              DEFAULT_BRANCH="<< trigger_parameters.gitlab.default_branch >>"; 
              AUTHOR="<< trigger_parameters.gitlab.commit_author_name >> <<< trigger_parameters.gitlab.commit_author_email >>>"
              COMMIT_TIMESTAMP="<< trigger_parameters.gitlab.commit_timestamp >>";
              NAMESPACE="<< trigger_parameters.gitlab.repo_name >>"
              REPOSITORY="<< trigger_parameters.gitlab.project_id >>"
              COMMIT_URL="<< trigger_parameters.gitlab.web_url >>/commit/$COMMIT_SHA";
            else
              DEFAULT_BRANCH="$(git remote show $(git remote) | sed -n '/HEAD branch/s/.*: //p')";
              AUTHOR="$(git log --format='%an <%ae>' $COMMIT_SHA^!)";
              MESSAGE="$(git log --format='%B' $COMMIT_SHA^!)";
              COMMIT_TIMESTAMP="$(git log --format=%ci $COMMIT_SHA^!)";
              REPOSITORY="$(basename `git rev-parse --show-toplevel`)";
              NAMESPACE=""
              COMMIT_URL=""
            fi

            IS_MAIN_BRANCH=false;
            
            if [[ $DEFAULT_BRANCH == $CURRENT_BRANCH ]]; then
              IS_MAIN_BRANCH=true;
            fi 
            
          
            # pushId=`npm run -s push -- docs/s-petstore.yaml \
            #   --organization 'default' \
            #   --project 'pushes-demo' \
            #   --mountPath 'docs/remotes/cicd' \
            #   --isMainBranch $IS_MAIN_BRANCH \
            #   --branch "$CURRENT_BRANCH" \
            #   --author "$AUTHOR" \
            #   --commitUrl "$COMMIT_URL" \
            #   --createdAt "$COMMIT_TIMESTAMP"
            #   --namespace "$NAMESPACE" \
            #   --repository "$REPOSITORY" \
            #   --message "$MESSAGE" \
            #   --domain 'https://app.lab1.blueharvest.cloud'`
            echo "VCS: $VCS , CURRENT_BRANCH: $CURRENT_BRANCH , COMMIT_SHA: $COMMIT_SHA, IS_MAIN_BRANCH: $IS_MAIN_BRANCH";
            echo "DEFAULT_BRANCH: $DEFAULT_BRANCH , AUTHOR: $AUTHOR, MESSAGE: $MESSAGE, PROVIDER: $PROVIDER";
            echo "COMMIT_TIMESTAMP: $COMMIT_TIMESTAMP, REPOSITORY: $REPOSITORY, COMMIT_URL: $COMMIT_URL, NAMESPACE: $NAMESPACE"
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  push-to-redocly:
    jobs:
      - push
