version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  push:
    docker:
      # TODO: use redocly/cli image
      - image: cimg/base:stable
    environment: 
      COMMIT_SHA: << pipeline.git.revision >>
      REPO_URL: << pipeline.project.git_url >>
      REPO_NAME: << pipeline.trigger_parameters.github_app.repo_name >>
      CURRENT_BRANCH: << pipeline.trigger_parameters.github_app.branch >>
      MESSAGE: << pipeline.trigger_parameters.github_app.commit_message >>
      COMMIT_TIMESTAMP: << pipeline.trigger_parameters.github_app.commit_timestamp >>
    steps:
      - checkout
      - node/install:
          node-version: "20.4.0"
      - node/install-packages
      - run:
          name: "Push files"
          command: |-
            REMOTE_INFO="$(git remote show $(git remote))";
            DEFAULT_BRANCH=$(echo "$REMOTE_INFO" | sed -n '/HEAD branch/s/.*: //p');
            AUTHOR="$(git log --format='%an <%ae>' $COMMIT_SHA^!)";
            NAMESPACE="$(basename $(echo "$REPO_URL" | sed "s/$REPO_NAME//p"))"
            COMMIT_URL="$REPO_URL/commit/$COMMIT_SHA";
            IS_MAIN_BRANCH=false;

            if [[ $DEFAULT_BRANCH == $CURRENT_BRANCH ]]; then
              IS_MAIN_BRANCH=true;
            fi

            PUSH_ID=`npm run -s push -- docs \
              --organization 'default' \
              --project 'push-rework' \
              --mountPath 'docs/remotes/cicd' \
              --isMainBranch $IS_MAIN_BRANCH \
              --branch "$CURRENT_BRANCH" \
              --author "$AUTHOR_NAME <$AUTHOR_EMAIL>" \
              --commitSha "$COMMIT_SHA" \
              --commitUrl "$COMMIT_URL" \
              --createdAt "$COMMIT_TIMESTAMP" \
              --repository "$REPO_NAME" \
              --namespace "$NAMESPACE" \
              --message "$MESSAGE" \
              --domain 'https://app.lab1.blueharvest.cloud'`

            npm run -s push-status $PUSH_ID \
              --organization 'default' \
              --project 'push-rework' \
              --domain 'https://app.lab1.blueharvest.cloud'`
workflows:
  prepare-config:
    jobs:
      - push
