version: 2.1
jobs:
  push:
    docker:
      - image: redocly/cli
    parameters:
      files:
        description: Files to push
        type: string
      organization:
        description: Organization name
        type: string
      project:
        description: Project name
        type: string
      mountPath:
        description: Mount path
        type: string
      commitSha:
        description: Commit SHA
        type: string
        default: '<< pipeline.git.revision >>'
      commitUrl:
        description: Commit URL
        type: string
      currentBranch:
        description: Current branch
        type: string
        default: '<< pipeline.git.branch >>'
      defaultBranch:
        description: Default branch
        type: string
        default: 'main'
      commitMessage:
        description: Commit message
        type: string
      commitTimestamp:
        description: Commit timestamp
        type: string
      repositoryUrl:
        description: Repository URL
        type: string
        default: '<< pipeline.project.git_url >>'
      repositoryName:
        description: Repository name
        type: string
      namespace:
        description: Repository owner
        type: string
        default: ''
      domain:
        description: Domain name
        type: string
        default: 'https://app.cloud.redocly.com'
    steps:
      - checkout
      - run:
          name: "Push files and wait for deployment"
          command: |-
            apk add --no-cache git;
            
            COMMIT_SHA="<< parameters.commitSha >>";
            REPO_NAME="<< parameters.repositoryName >>";
            NAMESPACE="<< parameters.namespace >>"
            NAMESPACE="$(basename $(echo "<< parameters.repositoryUrl >>" | sed "s/$REPO_NAME//p"))"

            redocly push << parameters.files >> \
              --organization "<< parameters.organization >>" \
              --project "<< parameters.project >>" \
              --mount-path "<< parameters.mountPath >>" \
              --default-branch "<< parameters.defaultBranch >>" \
              --branch "<< parameters.currentBranch >>" \
              --author "$(git log --format='%an <%ae>' $COMMIT_SHA^!)" \
              --commit-sha "$COMMIT_SHA" \
              --commit-url "<< parameters.commitUrl >>" \
              --created-at "<< parameters.commitTimestamp >>" \
              --repository "$REPO_NAME" \
              --namespace "$NAMESPACE" \
              --message "<< parameters.commitMessage >>" \
              --domain "<< parameters.domain >>" \
              --wait-for-deployment
workflows:
  push-to-redocly:
    jobs:
      - push:
          files: 'docs'
          organization: 'default'
          project: 'push-rework'
          mountPath: '/docs/remotes/cicd'
          domain: 'https://app.lab1.blueharvest.cloud'
          repositoryName: '<< pipeline.trigger_parameters.github_app.repo_name >>'
          commitMessage: '<< pipeline.trigger_parameters.github_app.commit_message >>'
          commitUrl: '<< pipeline.project.git_url >>/commit/<< pipeline.git.revision >>'
          commitTimestamp: '<< pipeline.trigger_parameters.github_app.commit_timestamp >>'
          defaultBranch: 'main'
          namespace: 'roman-sainchuk'