version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  push:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
    # TODO: use redocly/cli image
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    environment: 
      VCS: << pipeline.project.type >>
      PROVIDER: << pipeline.trigger_parameters.circleci.trigger_type >>
      CURRENT_BRANCH: << pipeline.git.branch >>
      COMMIT_SHA: << pipeline.git.revision >>
      AUTHOR_EMAIL: << pipeline.trigger_parameters.github_app.commit_author_email >>
      DEFAULT_BRANCH: << pipeline.trigger_parameters.github_app.default_branch >>
    steps:
      - checkout
      - run:
          name: "Push"
          
          command: |-
          
           
            
            IS_MAIN_BRANCH=false;
            
            if [[ $DEFAULT_BRANCH == $CURRENT_BRANCH ]]; then
              IS_MAIN_BRANCH=true;
            fi 
            
          
            # pushId=`npm run -s push -- docs/s-petstore.yaml \
            #   --organization 'default' \
            #   --project 'pushes-demo' \
            #   --mountPath 'docs/remotes/cicd' \
            #   --isMainBranch $IS_MAIN_BRANCH \
            #   --branch "$CURRENT_BRANCH" \
            #   --author "$AUTHOR" \
            #   --commitUrl "$COMMIT_URL" \
            #   --createdAt "$COMMIT_TIMESTAMP"
            #   --namespace "$NAMESPACE" \
            #   --repository "$REPOSITORY" \
            #   --message "$MESSAGE" \
            #   --domain 'https://app.lab1.blueharvest.cloud'`
            echo "VCS: $VCS , CURRENT_BRANCH: $CURRENT_BRANCH , COMMIT_SHA: $COMMIT_SHA, IS_MAIN_BRANCH: $IS_MAIN_BRANCH";
            echo "DEFAULT_BRANCH: $DEFAULT_BRANCH , AUTHOR: $AUTHOR, MESSAGE: $MESSAGE, PROVIDER: $PROVIDER";
            echo "COMMIT_TIMESTAMP: $COMMIT_TIMESTAMP, REPOSITORY: $REPOSITORY, COMMIT_URL: $COMMIT_URL, NAMESPACE: $NAMESPACE"
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  push-to-redocly:
    jobs:
      - push
